Allocator against new isolation service
Netflix-Skunkworks/titus-isolate pull request #337
Opened 2021-04-23 17:40 UTC by rostyboost

2021-04-26 19:02 UTC, gabrielhartmann commented on titus_isolate/allocate/constants.py
> +GRPC_CELL = "grpc_cell"
Why is this needed?  Shouldn't a client land in a particular cell regardless of implementation?  I'd expect the `get_cell` function to determine which API it should address and return the correct cell.

2021-04-26 19:03 UTC, gabrielhartmann commented on titus_isolate/utils.py
> +def get_grpc_cell_name():
Same comment as for the GRPC_CELL tag.

2021-04-26 19:08 UTC, gabrielhartmann commented on titus_isolate/allocate/remote/allocator.py
> +class Allocator(CpuAllocator):
Can we please name this something a bit less generic?
```
GrpcAllocator
```
maybe

2021-04-26 19:10 UTC, gabrielhartmann commented on titus_isolate/config/constants.py
> +GRPC_REMOTE_ALLOC_ENDPOINT = 'TITUS_ISOLATE_GRPC_REMOTE_ALLOCATOR_ENDPOINT'
You probably want all 3 of these in the "restart" list at the bottom of this file.

2021-04-26 19:10 UTC, gabrielhartmann commented on titus_isolate/utils.py
> +    endpoint = config_manager.get_str(GRPC_REMOTE_ALLOC_ENDPOINT, None)
If this function continues to exist, you probably want `get_cached_str` along with the inclusion in the "restart" list.

2021-04-26 19:11 UTC, gabrielhartmann commented on titus_isolate/allocate/remote/allocator.py
> +        self.__endpoint = config_manager.get_str(GRPC_REMOTE_ALLOC_ENDPOINT, None)
`get_cached_str`

2021-04-26 19:13 UTC, gabrielhartmann commented on titus_isolate/isolate/utils.py
> +from titus_isolate.allocate.remote.allocator import Allocator as GrpcRemoteIsolServiceAllocator
This is a 3rd name for the same allocator I think.

2021-04-26 19:15 UTC, gabrielhartmann requested changes
Please see comments.  I assume the core functionality of calling the GRPC service has been verified.  As long as we can return to using the current remote allocator, and dynamically configure the new GRPC remote allocator we should be good to go.

2021-04-29 17:39 UTC, rostyboost commented
Thanks @gabrielhartmann . I believe I addressed all comments in https://github.com/Netflix-Skunkworks/titus-isolate/pull/337/commits/354dc913a6ede8595ecbde98b99ce0ed693d70d0

2021-04-29 17:43 UTC, gabrielhartmann approved these changes

2021-04-29 17:47 UTC, merged